import { useEffect,useMemo,useState } from 'react';
import { getPokemonBundle,getSearchIndex } from '../api/pokeApi';
import { acceptableTypo,getFuzzyMatches } from '../utils/fuzzySearch';
import { compactText,titleCase } from '../utils/pokemonUtils';
import { buildDailyClues,dayKey,deterministicIndex } from '../utils/dailyGame';
const MAX=8;
export function useDailyGame(){const day=useMemo(()=>dayKey(),[]);const[target,setTarget]=useState(null);const[index,setIndex]=useState([]);const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState(null);
useEffect(()=>{let active=true;(async()=>{try{const all=await getSearchIndex();const candidates=all.filter(x=>x.id&&x.name&&!x.name.includes('totem'));const targetName=candidates[deterministicIndex(`pokelibrary-${day}`,candidates.length)].name;const targetBundle=await getPokemonBundle(targetName);const stored=JSON.parse(localStorage.getItem(`pokelibrary:daily:${day}`)||'[]');const rebuilt=[];for(const name of stored){try{const guess=await getPokemonBundle(name);rebuilt.push({name:guess.pokemon.name,win:guess.pokemon.name===targetBundle.pokemon.name,clues:buildDailyClues(guess,targetBundle)});}catch{}}if(active){setIndex(all);setTarget(targetBundle);setRows(rebuilt);}}catch(e){if(active)setError(e.message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[day]);
const won=rows.some(r=>r.win),finished=won||rows.length>=MAX;
async function guess(raw){if(finished)return;const q=compactText(raw);if(!q){setError('Escribe un Pokémon para intentar.');return;}let match=index.find(x=>compactText(x.name)===q);if(!match){const fuzzy=getFuzzyMatches(raw,index,1)[0];if(acceptableTypo(raw,fuzzy))match=fuzzy;}if(!match){setError('No encontré ese Pokémon. Prueba con otro nombre o forma.');return;}if(rows.some(r=>r.name===match.name)){setError('Ese Pokémon ya fue usado hoy.');return;}setLoading(true);setError(null);try{const bundle=await getPokemonBundle(match.name);const row={name:bundle.pokemon.name,win:bundle.pokemon.name===target.pokemon.name,clues:buildDailyClues(bundle,target)};const next=[...rows,row];setRows(next);localStorage.setItem(`pokelibrary:daily:${day}`,JSON.stringify(next.map(r=>r.name)));}catch(e){setError(e.message);}finally{setLoading(false);}}
return{day,target,rows,loading,error,won,finished,max:MAX,guess,targetName:finished?titleCase(target?.pokemon?.name||''):null};}
