import { useState } from 'react';
import { getSearchIndex,searchByType,getSpecialIndex } from '../api/pokeApi';
import { compactText,isDexNumber,parseDexNumber,typeLabel,titleCase } from '../utils/pokemonUtils';
import { getFuzzyMatches,acceptableTypo } from '../utils/fuzzySearch';
export function usePokemonSearch(){const [state,setState]=useState({loading:false,error:null,suggestions:[],results:[],title:'',message:''});
async function resolve(raw){const q=String(raw||'');if(!compactText(q))throw new Error('Escribe un nombre o número de Pokédex.');if(isDexNumber(q)){const id=parseDexNumber(q);if(!id)throw new Error('Número inválido.');return{id,correction:null,suggestions:[]};}const index=await getSearchIndex();const exact=index.find(x=>compactText(x.name)===compactText(q));if(exact)return{id:exact.name,correction:null,suggestions:[]};const matches=getFuzzyMatches(q,index,6),best=matches[0];if(acceptableTypo(q,best))return{id:best.name,correction:`No encontré “${q.trim()}” exactamente. Mostrando ${titleCase(best.name)}.`,suggestions:matches.slice(1)};return{id:null,correction:null,suggestions:matches};}
async function search(raw){setState(s=>({...s,loading:true,error:null,message:''}));try{const r=await resolve(raw);if(!r.id){setState(s=>({...s,loading:false,suggestions:r.suggestions,error:'No encontré una coincidencia suficientemente segura.'}));return r;}setState(s=>({...s,loading:false,suggestions:r.suggestions,message:r.correction||'Pokémon encontrado.'}));return r;}catch(error){setState(s=>({...s,loading:false,error:error.message}));return null;}}
async function filter(type,rarity){setState(s=>({...s,loading:true,error:null,suggestions:[]}));try{let results=[],parts=[];if(type){results=(await searchByType(type)).filter(x=>x.id);parts.push(`Tipo ${typeLabel(type)}`);}if(rarity){const special=getSpecialIndex(rarity);parts.push(rarity==='legendary'?'Legendarios':'Míticos');if(type){const ids=new Set(special.map(x=>x.id));results=results.filter(x=>ids.has(x.id));}else results=special;}const map=new Map();results.forEach(x=>{if(x.id&&!map.has(x.id))map.set(x.id,x);});results=[...map.values()].sort((a,b)=>a.id-b.id);setState(s=>({...s,loading:false,results,title:parts.join(' · '),message:`${results.length} resultado(s).`}));return results;}catch(error){setState(s=>({...s,loading:false,error:error.message}));return[];}}
function clear(){setState({loading:false,error:null,suggestions:[],results:[],title:'',message:''});}
return{...state,search,filter,clear};}
