import {useEffect,useState} from 'react';import {getPokemonBundle,getEvolutionChain} from '../api/pokeApi.js';import {buildDailyClues,dayKey,deterministicPokemonId} from '../utils/dailyGame.js';import {titleCase,padDex} from '../utils/pokemonUtils.js';import PixelPokemonSprite from '../components/common/PixelPokemonSprite.jsx';import {saveGameRecord} from '../utils/arcadeStorage.js';import {evolutionStageFromChain} from '../utils/dailyEvolution.js';
const clueClass=c=>c.match?'correct':c.partial?'partial':'wrong';
export default function DailyPage(){const [mode,setMode]=useState('daily'),[target,setTarget]=useState(null),[q,setQ]=useState(''),[guesses,setGuesses]=useState([]),[message,setMessage]=useState(''),[streak,setStreak]=useState(0),[attempts,setAttempts]=useState(0);
 async function enrich(bundle){const chain=await getEvolutionChain(bundle.species.evolution_chain?.url);return {...bundle,evolutionStage:evolutionStageFromChain(chain,bundle.species.name)}}
 async function loadTarget(){setGuesses([]);setAttempts(0);setMessage('');const id=mode==='daily'?deterministicPokemonId(dayKey()):Math.floor(Math.random()*1025)+1;try{const t=await enrich(await getPokemonBundle(id));setTarget(t);if(mode==='daily'){try{const saved=JSON.parse(localStorage.getItem(`crowleth:daily:${dayKey()}`)||'{}');const restored=[];for(const name of saved.guesses||[]){const g=await enrich(await getPokemonBundle(name));restored.push({bundle:g,clues:{...buildDailyClues(g,t),evolution:{value:g.evolutionStage,match:g.evolutionStage===t.evolutionStage}}});}setGuesses(restored.reverse());setAttempts(restored.length);}catch{}}}catch(e){setMessage(e.message)}}
 useEffect(()=>{loadTarget()},[mode]);
 async function guess(e){e.preventDefault();if(!q.trim()||!target)return;if((mode==='streak'&&attempts>=5)||(mode==='daily'&&attempts>=8)){setMessage('Se agotaron los intentos de esta ronda.');return;}try{const g=await enrich(await getPokemonBundle(q.trim().toLowerCase()));const clues=buildDailyClues(g,target);clues.evolution={value:g.evolutionStage,match:g.evolutionStage===target.evolutionStage};const win=g.species.id===target.species.id;const nextAttempts=attempts+1;setAttempts(nextAttempts);setGuesses(x=>[{bundle:g,clues},...x]);setQ('');if(mode==='daily'){try{const key=`crowleth:daily:${dayKey()}`;const saved=JSON.parse(localStorage.getItem(key)||'{}');localStorage.setItem(key,JSON.stringify({guesses:[...(saved.guesses||[]),g.pokemon.name],solved:win||saved.solved}))}catch{}}if(win){setMessage(`¡Correcto! Era ${titleCase(target.pokemon.name)}.`);if(mode==='streak'){const s=streak+1;setStreak(s);saveGameRecord('daily',{bestStreak:Math.max(s,Number(localStorage.getItem('crowleth:daily-best')||0))});localStorage.setItem('crowleth:daily-best',String(Math.max(s,Number(localStorage.getItem('crowleth:daily-best')||0))));setTimeout(loadTarget,900)}}else if(mode==='streak'&&nextAttempts>=5){setMessage(`Fin de la racha. Era ${titleCase(target.pokemon.name)}.`);setStreak(0);setTimeout(loadTarget,1400)}}catch(err){setMessage(err.message)}}
 return <GameFrame title="PokéDaily" subtitle={mode==='daily'?`Reto ${dayKey()}`:`Racha actual: ${streak}`}><div className="mode-switch"><button className={mode==='daily'?'active':''} onClick={()=>setMode('daily')}>Daily</button><button className={mode==='streak'?'active':''} onClick={()=>setMode('streak')}>Competitivo / Racha</button></div><form className="game-input" onSubmit={guess}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Escribe un Pokémon o número…"/><button>Probar</button></form>{message&&<p className="game-message">{message}</p>}<div className="daily-table-wrap"><table className="daily-table"><thead><tr><th>Pokémon</th><th>Nº</th><th>Gen</th><th>Tipo 1</th><th>Tipo 2</th><th>Altura</th><th>Peso</th><th>Rareza</th><th>Forma</th><th>Etapa</th></tr></thead><tbody>{guesses.map(({bundle:g,clues},i)=><tr key={`${g.pokemon.id}-${i}`}><td><PixelPokemonSprite id={g.species.id} name={g.pokemon.name}/><b>{titleCase(g.pokemon.name)}</b></td><td className={clueClass(clues.id)}>{padDex(g.pokemon.id)} {clues.id.direction}</td><td className={clueClass(clues.generation)}>{clues.generation.value}</td><td className={clueClass(clues.type1)}>{clues.type1.value}</td><td className={clueClass(clues.type2)}>{clues.type2.value}</td><td className={clueClass(clues.height)}>{g.pokemon.height/10}m {clues.height.direction}</td><td className={clueClass(clues.weight)}>{g.pokemon.weight/10}kg {clues.weight.direction}</td><td className={clueClass(clues.rarity)}>{clues.rarity.value}</td><td className={clueClass(clues.form)}>{clues.form.value}</td><td className={clueClass(clues.evolution)}>{clues.evolution.value}</td></tr>)}</tbody></table></div></GameFrame>}
function GameFrame({title,subtitle,children}){return <section className="game-shell"><header className="game-head"><div><span>CROWLETH POKÉDEX</span><h1>{title}</h1></div><b>{subtitle}</b></header>{children}</section>}
