import {useEffect,useMemo,useState} from 'react';
import {getPokemonBundle,getEvolutionChain,getTypeRelations,getVarietyDetails,getMove,getAbility} from '../api/pokeApi.js';
import {combineTypeRelations} from '../utils/typeRelations.js';
import {getOfficialArtwork,generationForId,getLocalSpriteUrl} from '../utils/assets.js';
import {getLocalizedEntry,padDex,statLabel,titleCase,describeEvolution,extractId} from '../utils/pokemonUtils.js';
import TypeBadge from '../components/common/TypeBadge.jsx';
import PixelPokemonSprite from '../components/common/PixelPokemonSprite.jsx';
import DefenseProfile from '../components/pokemon/DefenseProfile.jsx';
import {Link,navigate} from '../routes/router.jsx';

function flattenChain(node,depth=0,out=[]){if(!node)return out;out.push({name:node.species.name,id:extractId(node.species.url),depth,detail:node.evolution_details?.[0]});for(const child of node.evolves_to||[])flattenChain(child,depth+1,out);return out;}
export default function PokemonDetailPage({identifier}){const [bundle,setBundle]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('summary'),[shiny,setShiny]=useState(false),[extras,setExtras]=useState({});
 useEffect(()=>{let live=true;setLoading(true);setError('');setExtras({});getPokemonBundle(decodeURIComponent(identifier)).then(d=>live&&setBundle(d)).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false}},[identifier]);
 useEffect(()=>{if(!bundle)return;let live=true;(async()=>{try{if(tab==='evolution'&&!extras.evolution){const d=await getEvolutionChain(bundle.species.evolution_chain?.url);if(live)setExtras(x=>({...x,evolution:d}));}if(tab==='forms'&&!extras.forms){const d=await getVarietyDetails(bundle.species);if(live)setExtras(x=>({...x,forms:d}));}if(tab==='defenses'&&!extras.defenses){const d=await getTypeRelations(bundle.pokemon.types.map(t=>t.type.name));if(live)setExtras(x=>({...x,defenses:combineTypeRelations(d)}));}}catch{} })();return()=>{live=false}},[tab,bundle]);
 if(loading)return <div className="full-state">Consultando PokéAPI…</div>;if(error)return <div className="full-state error">{error}<Link to="/pokedex">Volver a la Pokédex</Link></div>;if(!bundle)return null;
 const {pokemon,species}=bundle;const name=titleCase(pokemon.name);const description=getLocalizedEntry(species.flavor_text_entries,'flavor_text');const genus=getLocalizedEntry(species.genera,'genus');const artwork=getOfficialArtwork(pokemon,shiny);const tabs=[['summary','Resumen'],['stats','Estadísticas'],['evolution','Evolución'],['forms','Formas'],['defenses','Defensas'],['moves','Movimientos']];
 return <section className="pokemon-detail"><div className="pokemon-toolbar"><button onClick={()=>navigate(`/pokedex/${Math.max(1,pokemon.id-1)}`)}>← Anterior</button><span>{padDex(pokemon.id)} / #1025</span><button onClick={()=>navigate(`/pokedex/${Math.min(1025,pokemon.id+1)}`)}>Siguiente →</button></div><div className="pokemon-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div><div className="detail-sheet"><header className="detail-heading"><div><span className="kicker">{padDex(pokemon.id)} · Generación {generationForId(species.id)}</span><h1>{name}</h1><p>{genus}</p><div className="type-row">{pokemon.types.map(t=><TypeBadge key={t.type.name} type={t.type.name}/>)}</div></div><div className="art-stage"><img src={artwork||getLocalSpriteUrl(species.id)} alt={name}/><label className="shiny-toggle"><input type="checkbox" checked={shiny} onChange={e=>setShiny(e.target.checked)}/><span>{shiny?'✨ Shiny':'Normal'}</span></label></div></header><div className="tab-panel">{tab==='summary'&&<Summary pokemon={pokemon} species={species} description={description}/>} {tab==='stats'&&<Stats pokemon={pokemon}/>} {tab==='evolution'&&<Evolution chain={extras.evolution}/>} {tab==='forms'&&<Forms forms={extras.forms} current={pokemon.name}/>} {tab==='defenses'&&<DefenseProfile profile={extras.defenses||{}}/>} {tab==='moves'&&<Moves pokemon={pokemon}/>}</div></div></section>}
function Summary({pokemon,species,description}){const [abilityText,setAbilityText]=useState({});useEffect(()=>{let live=true;Promise.allSettled(pokemon.abilities.map(a=>getAbility(a.ability.url))).then(items=>{if(!live)return;const next={};items.forEach((x,i)=>{if(x.status==='fulfilled'){const entry=x.value.effect_entries?.find(e=>e.language?.name==='en');next[pokemon.abilities[i].ability.name]=entry?.short_effect||entry?.effect||'';}});setAbilityText(next)});return()=>{live=false}},[pokemon.id]);const gender=species.gender_rate<0?'Sin género':species.gender_rate===0?'100% macho':species.gender_rate===8?'100% hembra':`${Math.round((8-species.gender_rate)/8*100)}% ♂ · ${Math.round(species.gender_rate/8*100)}% ♀`;return <div className="summary-grid"><div className="info-card"><h3>Datos biológicos</h3><dl><dt>Altura</dt><dd>{pokemon.height/10} m</dd><dt>Peso</dt><dd>{pokemon.weight/10} kg</dd><dt>Género</dt><dd>{gender}</dd><dt>Experiencia base</dt><dd>{pokemon.base_experience??'—'}</dd><dt>Hábitat</dt><dd>{titleCase(species.habitat?.name||'Desconocido')}</dd></dl></div><div className="info-card wide"><h3>Entrada Pokédex</h3><p className="flavor">{description||'No hay una descripción localizada disponible.'}</p><h4>Habilidades</h4><div className="ability-list verbose">{pokemon.abilities.map(a=><span key={a.ability.name}><b>{titleCase(a.ability.name)} {a.is_hidden&&<em>Oculta</em>}</b><small>{abilityText[a.ability.name]||'Consultando descripción…'}</small></span>)}</div></div></div>}
function Stats({pokemon}){const total=pokemon.stats.reduce((a,s)=>a+s.base_stat,0);return <div className="stats-card"><div className="bst"><span>BST</span><strong>{total}</strong></div>{pokemon.stats.map(s=><div className="stat-line" key={s.stat.name}><span>{statLabel(s.stat.name)}</span><div><i style={{width:`${Math.min(100,s.base_stat/2)}%`}}/></div><b>{s.base_stat}</b></div>)}</div>}
function Evolution({chain}){if(!chain)return <p className="state">Cargando árbol evolutivo…</p>;const items=flattenChain(chain.chain);return <div className="evo-flow">{items.map((e,i)=><div className="evo-node" key={`${e.name}-${i}`}><PixelPokemonSprite id={e.id} name={e.name} fallback={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${e.name}.png`}/><b>{titleCase(e.name)}</b><small>{e.depth===0?'Especie inicial':describeEvolution(e.detail||{})}</small></div>)}</div>}
function Forms({forms,current}){if(!forms)return <p className="state">Buscando variedades…</p>;return <div className="forms-grid-new">{forms.map(f=><button key={f.name} className={f.name===current?'active':''} onClick={()=>navigate(`/pokedex/${f.name}`)}><img src={getOfficialArtwork(f)||f.sprites.front_default} alt=""/><b>{titleCase(f.name)}</b><small>{f.name===current?'Forma actual':'Abrir variante'}</small></button>)}</div>}
function Moves({pokemon}){const [selected,setSelected]=useState(pokemon.moves[0]?.move?.name||'');const [detail,setDetail]=useState(null);const sorted=useMemo(()=>pokemon.moves.slice(0,180),[pokemon.id]);useEffect(()=>{let live=true;if(!selected)return;setDetail(null);const ref=pokemon.moves.find(m=>m.move.name===selected)?.move?.url||selected;getMove(ref).then(d=>live&&setDetail(d)).catch(()=>{});return()=>{live=false}},[selected,pokemon.id]);const flavor=detail?.flavor_text_entries?.find(e=>e.language?.name==='es')?.flavor_text||detail?.flavor_text_entries?.find(e=>e.language?.name==='en')?.flavor_text||'';return <div className="moves-layout"><div className="moves-list">{sorted.map(m=><button key={m.move.name} className={selected===m.move.name?'active':''} onClick={()=>setSelected(m.move.name)}>{titleCase(m.move.name)}</button>)}</div><div className="move-detail"><span>Movimiento seleccionado</span><h3>{titleCase(selected)}</h3>{detail?<><div className="move-meta"><b>{typeLabel(detail.type?.name)}</b><b>{titleCase(detail.damage_class?.name||'')}</b><b>Pot. {detail.power??'—'}</b><b>Prec. {detail.accuracy??'—'}</b><b>PP {detail.pp??'—'}</b></div><p>{flavor.replace(/[\n\f\r]+/g,' ')||'Sin descripción disponible.'}</p></>:<p>Consultando detalle del movimiento…</p>}</div></div>}
